all: modules
	@sleep 0.1

modules: module01 module02 module03
	@sleep 0.2

module01:
	echo "module01"
	@sleep 0.4

module02:
	echo "module02"
	@sleep 0.125

module03:
	echo "module03"
	@sleep 0.25

.PHONY: module01 module02 module03 modules all
